import React, { useState } from 'react';
import Image from "next/image";
import {CloseIcon, WatchVideo} from "./../../components/icons"
const AICallSummary = () => {
     const [isVideoOpen, setIsVideoOpen] = useState(false);
    
      const handleWatchVideo = () => {
        setIsVideoOpen(true);
      };
    
      const closeVideo = () => {
        setIsVideoOpen(false);
      };
  return (
    <div className=" flex items-center justify-center">
      <div className=" rounded-lg py-6 w-full max-w-7xl flex flex-col md:flex-row items-center gap-6">
        <div className="w-[40%] py-4">
          <h2 className="text-[30px] font-bold o2-title mb-4">ServiceDesk AI</h2>
          <p className="text-gray-600 mb-4">
            An AI phone call summary is an automated recap of a phone conversation generated by artificial intelligence, providing a concise and insightful overview of key discussion points, action items, and caller sentiment from a transcript. This technology, used by businesses and professionals, helps improve agent performance by reducing manual note-taking, offers actionable insights for better customer interactions, and provides searchable records for follow-up and team performance analysis. Transform IVR phone calls into actionable insights instantly. Our AI technology integrates every conversation with ServiceNow; these summary documents are available by default, and customization can be done to load the PDFs into target applications.
          </p>
          <div className="flex space-x-4">
            <button className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
              Explore ServiceDesk AI
            </button>
            <button className="o2-title flex gap-2 items-center" onClick={handleWatchVideo} >Watch video <WatchVideo/></button>
          </div>
        </div>
        <div className="w-[60%] py-4 text-center">
            <Image
                 src="/AICallSummary.svg"
                 alt="I Search"
                 width={763}
                 height={653}
                 className="imagfilter m-auto"
               />
        </div>
      </div>
      {isVideoOpen && (
              <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50" onClick={closeVideo}>
                <div className="bg-white p-12 rounded-lg w-[900px] relative desing-boxmission">
                  <video controls autoPlay>
                    <source src="/video/AICallSummary.mp4" type="video/mp4" />
                    Your browser does not support the video tag.
                  </video>
                  <button
                    className="mt-4 text-white px-4 py-2 rounded absolute top-[-8px] right-0"
                    onClick={closeVideo}
                  >
                    <CloseIcon  width={60} height={60}/>
                  </button>
                </div>
              </div>
            )}
    </div>
  );
};

export default AICallSummary;