import React, { useState } from 'react';
import Image from 'next/image';
import {
  AiCallSummary,
  AISearch,
  AIOpsIcon,
  ClinicalAI,
  FaxAutomation,
  EmployeeEnablement,
  IVR,
} from "./../../components/icons";
import { XMarkIcon } from '@heroicons/react/24/outline'; // Optional close icon

// Product data array (better than hardcoding in JSX)
const products = [
  {
    icon: <AiCallSummary />,
    title: "ServiceDesk AI",
    description: "ServiceDesk AI captures key call points, emotions, and sentiments from IVR interactions.",
    popupContent: "An AI phone call summary is an automated recap of a phone conversation generated by artificial intelligence, providing a concise and insightful overview of key discussion points, action items, and caller sentiment from a transcript. This technology, used by businesses and professionals, helps improve agent performance by reducing manual note-taking, offers actionable insights for better customer interactions, and provides searchable records for follow-up and team performance analysis. Transform IVR phone calls into actionable insights instantly. Our AI technology from every conversation integrates to ServiceNow; these summary documents are available by default to ServiceNow customization can be done to load the PDF to target applications.",
    popupImages: "/AICallSummary.svg"
  },
  {
    icon: <ClinicalAI />,
    title: "ClinicalAI",
    description: "AI medical scribes automate clinical documentation and complete the charting for providers and nurses in SOAP format.",
    popupContent: "AI medical scribe for all clinicians. This module is the ambient AI medical scribe that automates clinical documentation to reduce administrative burdens and enable healthcare professionals to focus more on patient care. It stores the raw text in the EHR platform along with the summarized view. The module is also integrated with ICD-10. This module is developed in accordance with HIPAA; the conversation and chart summary are stored in the clients premises (cloud).",
    popupImages: "/ClinicalAI.svg"
  },
  {
    icon: <FaxAutomation />,
    title: "Fax Automation",
    description: "AI Fax automation reads, classifies, and routes faxes automatically, reducing manual work for healthcare staff. It uses NLP to extract data accurately, speeding up the workflow.",
    popupContent: "Fax automation AI uses artificial intelligence to automatically read, classify, and extract data from incoming faxes, then routes it to the correct patient charts or systems, significantly reducing manual tasks for healthcare staff. This technology uses natural language processing to understand unstructured data, improving accuracy and speed in patient communication and administrative workflows, ultimately improving efficiency and freeing staff to focus on patient care.",
    popupImages: "/FaxAutomation-Img.png"
  },
  {
    icon: <AIOpsIcon />,
    title: "AI Ops",
    description: "AIOps automates and streamlines operational work by analyzing data from multiple sources and auto-remediating issues.",
    popupContent: "AIOps stands for Artificial Intelligence for IT Operations and is the strategic use of AI and machine learning (ML) to automate and streamline IT operations. It analyzes large volumes of data from various IT sources to provide insights like anomaly detection, root cause analysis, and automated remediation, which helps prevent issues before they impact users and speeds up problem resolution. This allows IT teams to manage complexity, reduce costs, and improve efficiency in modern IT environments.",
    popupImages: "/AIOps.svg"
  },
  {
    icon: <IVR />,
    title: "IVRAI",
    description: "AI-powered agentic IVR autonomously understands, converses with, and acts on customer requests, surpassing traditional IVR systems.",
    popupContent: "An AI phone call summary is an automated recap of a phone conversation generated by artificial intelligence, providing a concise and insightful overview of key discussion points, action items, and caller sentiment from a transcript. This technology, used by businesses and professionals, helps improve agent performance by reducing manual note-taking, offers actionable insights for better customer interactions, and provides searchable records for follow-up and team performance analysis. Transform IVR phone calls into actionable insights instantly. Our AI technology from every conversation integrates to ServiceNow; these summary documents are available by default to ServiceNow customization can be done to load the PDF to target applications.",
    popupImages: "/AISearch.svg"
  },
  {
    icon: <AISearch width={70} />,
    title: "AI Search",
    description: "AI chatbots streamline recruitment by automating resume screening, sourcing, and scheduling. They quickly identify top candidates for each role.",
    popupContent: "Easy to configure, straight to the point – our chatbots will strike up conversations effortlessly with candidates. It summarizes the resume with key points and compares it with other resumes to make it easier for recruiters to streamline the selection process. AI-powered automation improves recruitment by handling time-consuming, repetitive tasks like resume screening, candidate sourcing, and interview scheduling. It can process large volumes of data much faster and more accurately than humans, identifying the top candidates for specific roles based on job requirements.",
    popupImages: "/AISearch.svg"
  },
  {
    icon: <EmployeeEnablement width={70} />,
    title: "Employee Enablement",
    description: "A single AI-enabled interface centralizes insights from Finance, HR, Claims, Members, Providers, UM/CM, Enrollment, and more for streamlined access and management.",
    popupContent: "A single AI-enabled screen interface offers insights across various systems including Finance, HR, Claims, Members, Providers, Vendors, UM/CM, Enrollment, Products and more, simplifying access to vital data. Effortless dataset configurations streamline management, ensuring seamless operations across all domains. This system's efficiency not only boosts productivity but also reduces costs associated with corporate reporting significantly. Centralizing data access eliminates the necessity for multiple reporting platforms, leading to substantial savings for the organization. This consolidated approach not only enhances decision-making but also optimizes resource allocation, ultimately contributing to financial savings. Furthermore, this tool will be developed in-house.",
    popupImages: "/EmployeeEnablement1.svg"
  },
  {
    icon: <AISearch width={70} />,
    title: "Staff Augmentation",
    description: "O2AI offers an AI-assisted development team to empower your internal team with our expertise in artificial intelligence solutions and augmentation.",
    popupContent: "O2AI offers an AI-assisted development team to empower your internal team with our expertise in artificial intelligence solutions and augmentation.",
    popupImages: "/AISearch.svg"
  },
];

const OurAIProducts = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedProduct, setSelectedProduct] = useState<typeof products[0] | null>(null);

  const openModal = (product: typeof products[0]) => {
    setSelectedProduct(product);
    setIsModalOpen(true);
    document.body.style.overflow = 'hidden'; // Prevent background scroll
  };

  const closeModal = () => {
    setIsModalOpen(false);
    setSelectedProduct(null);
    document.body.style.overflow = 'unset';
  };

  return (
    <>
      <div className="py-12 px-4 pt-16 product-padding">
        <h2 className="text-[40px] font-bold text-center mt-8 mb-12 o2-title leading-[1.2]">
          Our AI product helps make your  <br /> operations faster, safer, and better.
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-7xl mx-auto">
          {products.map((product, index) => (
            <div
              key={index}
              className="bg-white p-8 rounded-lg shadow-md hover:shadow-xl transition-all duration-300 cursor-pointer transform hover:-translate-y-1 overEffect"
              onClick={() => openModal(product)}
            >
              <div className="flex items-center gap-3 mb-4">
                {product.icon}
                <h3 className="text-[18px] font-semibold o2-title">{product.title}</h3>
              </div>
              <p className="text-gray-600 text-sm leading-relaxed">
                {product.description}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Modal / Popup */}
      {isModalOpen && selectedProduct && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black bg-opacity-60 backdrop-blur-sm" onClick={closeModal}>
          <div
            className="relative bg-white rounded-2xl shadow-2xl  w-[70%] max-h-screen overflow-y-auto animate-in fade-in zoom-in duration-300 p-12"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="p-8 ">
              {/* Close Button */}
              <button
                onClick={closeModal}
                className="absolute top-4 right-4 text-gray-500 hover:text-gray-800 transition"
                aria-label="Close modal"
              >
                <XMarkIcon className="w-8 h-8" />
              </button>

              <div className='flex gap-6 items-top'>
                 {selectedProduct.icon}
                  <div className="text-gray-700 text-lg leading-relaxed w-[60%] h-[320px]">
                    <h3 className="text-2xl font-bold o2-title">{selectedProduct.title}</h3>
                    {selectedProduct.popupContent}
                  </div>
                  {/* Image (if exists) */}
                  {selectedProduct.popupImages && (
                    <div className="mb-8 -mx-8 w-[40%] h-[320px] flex justify-center">
                      <Image 
                        src={selectedProduct.popupImages}
                        alt={`${selectedProduct.title} screenshot`}
                        width={300}
                        height={320}
                        className="w-full"
                      />
                    </div>
                  )}
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default OurAIProducts;